//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pertes
    {
        public int Id_Pert { get; set; }
        public string Descrip { get; set; }
        public Nullable<System.DateTime> datePert { get; set; }
        public Nullable<double> valeur { get; set; }
    }
}
