//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id_Reservation { get; set; }
        public string CIN { get; set; }
        public Nullable<int> id_Maison { get; set; }
        public Nullable<System.DateTime> dateDebut { get; set; }
        public Nullable<System.DateTime> dateFin { get; set; }
        public Nullable<double> avance { get; set; }
        public Nullable<System.DateTime> date_reservation { get; set; }
        public Nullable<double> prix { get; set; }
        public Nullable<bool> etat { get; set; }
        public Nullable<int> duree { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Maison Maison { get; set; }
    }
}
